apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana.yaml
  - intel.yaml
  - jetstack.yaml
  - openebs.yaml
  - rook-ceph.yaml
  - vector.yaml
  - victoria-metrics.yaml
