apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: miroir
  namespace: flux-system
spec:
  interval: 12h
  type: oci
  url: oci://ghcr.io/home-operations/charts
  provider: generic
