---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: cloudflare-origin
spec:
  requestType: OriginRSA
  auth:
    tokenRef:
      name: cloudflare-origin-ca-token
      key: api-token