---
apiVersion: origin-ca-issuer.io/v1
kind: OriginIssuer
metadata:
  name: cloudflare-origin
spec:
  requestDuration: 0
  ref:
    name: cloudflare-origin-ca-token
    namespace: cert-manager
    key: api-token
