---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
  namespace: downloads
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: metube
    namespace: downloads
  install:
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - whoverse-w1
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    controllers:
      metube:
        strategy: Recreate
        containers:
          metube:
            image:
              repository: ghcr.io/alexta69/metube
              tag: 2026.09.26@sha256:8a72943fe6d29d23133aa4591117a423ec86708c227665e78a6e903554431bb4
            env:
              TZ: "America/Chicago"
              CHOWN_DIRS: "false"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8081
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8081
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  failureThreshold: 3
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
    service:
      metube:
        controller: metube
        ports:
          http:
            port: 8081
    persistence:
      downloads:
        type: persistentVolumeClaim
        existingClaim: media-youtube
        globalMounts:
          - path: /downloads