---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cilium
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
    require-cni.flux.home.arpa/disabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-gateway-api
  interval: 10m
  path: "./kubernetes/apps/kube-system/cilium/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cilium-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
    require-cni.flux.home.arpa/disabled: "true"
spec:
  dependsOn:
    - name: cluster-apps-cilium
  interval: 10m
  path: "./kubernetes/apps/kube-system/cilium/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
