---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/miroir.home-operations.com/miroirnodegroup_v1alpha1.json
apiVersion: miroir.home-operations.com/v1alpha1
kind: MiroirNodeGroup
metadata:
  name: cluster
spec:
  nodeSelector:
    matchLabels:
      miroir.home-operations.com/enabled: "true"
  template:
    pools:
      - name: replicated
        lvmthin:
          device: /dev/disk/by-partlabel/r-miroir
