---
autoDirectNodeRoutes: true
containerRuntime:
  integration: containerd
endpointRoutes:
  enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.0.0.0/8
k8sServiceHost: 192.168.3.2
k8sServicePort: 6443
kubeProxyReplacement: strict
loadBalancer:
  algorithm: maglev
  mode: dsr
localRedirectPolicy: true
operator:
  rollOutPods: true
rollOutCiliumPods: true
securityContext:
  privileged: true
tunnel: disabled
