---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: barcodebuddy
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: barcodebuddy
    namespace: default
  install:
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    controllers:
      barcodebuddy:
        containers:
          barcodebuddy:
            image:
              repository: f0rc3/barcodebuddy
              tag: latest@sha256:bcba09b8a1e950ab51df653737f43d20c1b68aedb8ad19a8e7b4d23a0bffdf16
            env:
              TZ: America/Chicago
              BBUDDY_EXTERNAL_GROCY_URL: https://grocy.whoverse.nexus
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      barcodebuddy:
        controller: barcodebuddy
        ports:
          http:
            port: 80

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        dataSourceRef:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: barcodebuddy
        globalMounts:
          - path: /config
