---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/alert_v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Alert
metadata:
  name: holmes
  namespace: holmes
spec:
  providerRef:
    name: holmes
  eventSources:
    - kind: Kustomization
      name: "*"
      namespace: "*"
    - kind: HelmRelease
      name: "*"
      namespace: "*"
  exclusionList:
    - ".*health-check.*"
  suspend: false
