---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: echo-server
spec:
  parentRefs:
    - name: web
      namespace: networking
  hostnames:
    - "echo-server.whoverse.dev"
  rules:
    - backendRefs:
        - name: echo-server
          port: 8080
