---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agent-sandbox-controller
  namespace: agent-sandbox-system
spec:
  interval: 15m
  path: "./infrastructure/agent-sandbox-system/agent-sandbox-controller/app"
  sourceRef:
    kind: OCIRepository
    name: home-ops
    namespace: flux-system
  timeout: 10m
  wait: true
  prune: true