creation_rules:
  # Bootstrap secrets - age + GPG (both recipients can decrypt)
  - path_regex: kubernetes/bootstrap/.*\.sops\.yaml$
    age: >-
      age16865gej0ndnlnghdq347fur59ht8d7wrcfptdw5ja4fhc4lwdfpq59ratl
    pgp: >-
      B2266723EDB691FBB16501BC07D6E31CCAE33514

  # Talos secrets - same age + GPG key set
  - path_regex: talos/.*\.sops\.yaml$
    age: >-
      age16865gej0ndnlnghdq347fur59ht8d7wrcfptdw5ja4fhc4lwdfpq59ratl
    pgp: >-
      B2266723EDB691FBB16501BC07D6E31CCAE33514
