---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-external-secrets
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dex-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_OIDC_DISCOVERY_URL
      remoteRef:
        key: dex-authentik-connector
        property: oidc-discovery-url
    - secretKey: AUTHENTIK_CLIENT_ID
      remoteRef:
        key: dex-authentik-connector
        property: client-id
    - secretKey: AUTHENTIK_CLIENT_SECRET
      remoteRef:
        key: dex-authentik-connector
        property: client-secret
    - secretKey: ENVOY_EXTERNAL_CLIENT_SECRET
      remoteRef:
        key: dex-clients
        property: envoy-external-secret
