---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: envoy-gateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - network
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-gateway
  endpoints:
    - port: metrics
      path: /metrics
