---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
  namespace: kopiur-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kopiur
      version: "0.7.5"
      sourceRef:
        kind: HelmRepository
        name: home-operations
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    features:
      credentialProjection:
        enabled: true
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 2Gi
