---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: pve-relay-tls
  namespace: network
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: pve-relay
  validation:
    caCertificateRefs:
      - name: pve-ca
        group: ""
        kind: Secret
    hostname: pve1.tailnet-f088.ts.net