---
apiVersion: v1
kind: Service
metadata:
  name: moltbot-egress
  namespace: network
  annotations:
    tailscale.com/tailnet-fqdn: "moltbot.tailnet-f088.ts.net."
    tailscale.com/proxy-group: moltbot-egress
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: searxng
      port: 8080
      protocol: TCP
    - name: memini
      port: 8081
      protocol: TCP