---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  path: "./infrastructure/cert-manager/cert-manager/app"
  sourceRef:
    kind: OCIRepository
    name: home-ops
    namespace: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-webhook
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-cainjector
      namespace: cert-manager
  timeout: 10m
  wait: true
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
    - name: external-secrets-config
      namespace: external-secrets-system
  interval: 10m
  path: "./infrastructure/cert-manager/cert-manager/config"
  sourceRef:
    kind: OCIRepository
    name: home-ops
    namespace: flux-system
  timeout: 5m
  wait: true
  prune: false
