---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    controllers:
      grocy:
        containers:
          grocy:
            image:
              repository: lscr.io/linuxserver/grocy
              tag: latest
            env:
              TZ: America/Chicago
              GROCY_BASE_URL: https://grocy.whoverse.nexus
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      grocy:
        controller: grocy
        ports:
          http:
            port: 80

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-rbd
        globalMounts:
          - path: /config
