# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: whoverse
  credentialProjection:
    enabled: true
  sources:
    - pvc:
        name: ${APP}-shared
    - pvc:
        name: ${APP}-redis-data
    - pvc:
        name: ${APP}-mariadb-data
  retention:
    keepDaily: 7
    keepWeekly: 4
    keepMonthly: 3
