---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-github-app
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-github-app
    creationPolicy: Owner
  data:
    - secretKey: appClientId
      remoteRef:
        key: konflate-github-app
        property: appClientId
    - secretKey: appPrivateKey
      remoteRef:
        key: konflate-github-app
        property: file/whoverse-konflate.2026-07-25.private-key.pem
