---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: konflate
      version: "0.4.3"
      sourceRef:
        kind: HelmRepository
        name: home-operations
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  valuesFrom:
    - kind: Secret
      name: konflate-github-app
      valuesKey: appClientId
      targetPath: config.appClientId
    - kind: Secret
      name: konflate-github-app
      valuesKey: appPrivateKey
      targetPath: secret.appPrivateKey
  values:
    replicaCount: 1
    serviceAccount:
      automount: false
    persistence:
      enabled: true
      size: 5Gi
      storageClass: ceph-rbd
      accessModes:
        - ReadWriteOnce
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 1
    config:
      repo: github://AlinaNova21/home-ops
      clusterPath: kubernetes
      statusChecks: true
      prComments: true
      publicUrl: https://konflate.whoverse.nexus
      mcp: true
      logLevel: debug
