---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: error-pages-internal
  namespace: default
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.2.4
    digest: sha256:4cfbba3ddffedc972814c1b3035cf9f6fb72ee68891921475c9606eb34a2bd84
  url: oci://ghcr.io/tarampampam/error-pages/charts/error-pages
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: ^https://token.actions.githubusercontent.com$
        subject: ^https://github.com/tarampampam/error-pages.*$
