---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: "./flux-config"
  sourceRef:
    kind: OCIRepository
    name: home-ops
  healthChecks:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: FluxInstance
      name: flux
      namespace: flux-system
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: flux-operator
      namespace: flux-system
  timeout: 10m
  wait: true
  prune: true
