---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-credentials
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflared-credentials
    creationPolicy: Owner
  data:
    - secretKey: tunnel-id
      remoteRef:
        key: cloudflare-tunnel-token
        property: tunnel-id
    - secretKey: tunnel-token
      remoteRef:
        key: cloudflare-tunnel-token
        property: credential
