---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-anime-config
  namespace: downloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-anime-config
    creationPolicy: Owner
  data:
    - secretKey: apikey
      remoteRef:
        key: sonarr
        property: credential
