apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease-operator.yaml
  - helmrelease-cluster.yaml
  - helmrelease-csi-drivers.yaml
  - httproute.yaml
  - pushsecret.yaml
