---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ceph-dashboard
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: rook-ceph-dashboard-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: ceph-dashboard
          property: password
