# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vmstorage-0
  namespace: monitoring
spec:
  policyRef:
    name: vmstorage-0
  schedule:
    cron: H * * * *
    runOnCreate: true
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vmstorage-1
  namespace: monitoring
spec:
  policyRef:
    name: vmstorage-1
  schedule:
    cron: H * * * *
    runOnCreate: true
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vmstorage-2
  namespace: monitoring
spec:
  policyRef:
    name: vmstorage-2
  schedule:
    cron: H * * * *
    runOnCreate: true
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vlstorage-0
  namespace: monitoring
spec:
  policyRef:
    name: vlstorage-0
  schedule:
    cron: H * * * *
    runOnCreate: true
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: vlstorage-1
  namespace: monitoring
spec:
  policyRef:
    name: vlstorage-1
  schedule:
    cron: H * * * *
    runOnCreate: true
