---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: discord-webhook
    creationPolicy: Owner
  data:
    - secretKey: URL
      remoteRef:
        key: webhook-discord-k8s
        property: URL