---
apiVersion: v1
kind: Namespace
metadata:
  name: notifications
  labels:
    app.kubernetes.io/name: notifications
    app.kubernetes.io/component: application
    homelab.whoverse.dev/component: apps
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
