---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-radarr.yaml
  - configmap-sonarr.yaml
  - externalsecret.yaml
  - cronjob-radarr.yaml
  - cronjob-sonarr.yaml
