apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kasm-secrets
  namespace: kasm
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kasm-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: kasm-postgres
        property: password
    - secretKey: admin-password
      remoteRef:
        key: kasm-auth
        property: admin-password
    - secretKey: user-password
      remoteRef:
        key: kasm-auth
        property: user-password
    - secretKey: manager-token
      remoteRef:
        key: kasm-auth
        property: manager-token
    - secretKey: service-token
      remoteRef:
        key: kasm-auth
        property: service-token