---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.13.2
  interval: 30m

  values:
    autoDirectNodeRoutes: true
    containerRuntime:
      integration: containerd
    endpointRoutes:
      enabled: true
    hubble:
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.0.0.0/8
    k8sServiceHost: kube.cluster.whoverse.dev
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true
    operator:
      rollOutPods: true
    rollOutCiliumPods: true
    securityContext:
      privileged: true
    tunnel: disabled
    bgpControlPlane:
      enabled: true
    gatewayAPI:
      enabled: false
