---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - httproute.yaml
  - grafana.yaml
  - folders.yaml
  - servicemonitor.yaml
  - dashboards/ceph-cluster.yaml
  - dashboards/ceph-osd.yaml
  - dashboards/cilium-agent.yaml
  - dashboards/cilium-operator.yaml
  - dashboards/flux-cluster.yaml
  - dashboards/hubble.yaml
  - dashboards/kubernetes-cluster.yaml
  - dashboards/media-dashboard.yaml
  - dashboards/radarr-v3.yaml
  - dashboards/sonarr-v3.yaml
