---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mailpit
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mailpit
    namespace: default
  install:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    global:
      labels:
        app.kubernetes.io/name: mailpit
        app.kubernetes.io/component: mail-testing

    controllers:
      mailpit:
        containers:
          mailpit:
            image:
              repository: axllent/mailpit
              tag: v1.31.1@sha256:98b916bd3c8d61f7633a52d3ea2f58d00620cb01ca57ab59edde68c347a95365
              pullPolicy: Always
            env:
              MP_MAX_MESSAGES: 5000
              MP_DATABASE: /data/mailpit.db
              MP_SMTP_AUTH_ACCEPT_ANY: 1
              MP_SMTP_AUTH_ALLOW_INSECURE: 1
            ports:
              - name: http
                containerPort: 8025
                protocol: TCP
              - name: smtp
                containerPort: 1025
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      mailpit:
        controller: mailpit
        ports:
          http:
            port: 8025
            targetPort: http
            protocol: TCP
          smtp:
            port: 1025
            targetPort: smtp
            protocol: TCP

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        dataSourceRef:
          apiGroup: kopiur.home-operations.com
          kind: Restore
          name: mailpit
        advancedMounts:
          mailpit:
            mailpit:
              - path: /data
