---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile-config
  namespace: sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: seafile-config
    creationPolicy: Owner
  data:
    - secretKey: admin_email
      remoteRef:
        key: seafile
        property: username
    - secretKey: admin_password
      remoteRef:
        key: seafile
        property: credential
    - secretKey: jwt_private_key
      remoteRef:
        key: seafile
        property: jwt_private_key
    - secretKey: mysql_root_password
      remoteRef:
        key: seafile
        property: mysql_root_password
    - secretKey: mysql_password
      remoteRef:
        key: seafile
        property: mysql_password
    # S3/Backblaze storage
    - secretKey: s3_key_id
      remoteRef:
        key: backblaze-seafile
        property: username
    - secretKey: s3_secret_key
      remoteRef:
        key: backblaze-seafile
        property: credential
    - secretKey: s3_bucket_commits
      remoteRef:
        key: backblaze-seafile
        property: bucket_commits
    - secretKey: s3_bucket_fs
      remoteRef:
        key: backblaze-seafile
        property: bucket_fs
    - secretKey: s3_bucket_blocks
      remoteRef:
        key: backblaze-seafile
        property: bucket_blocks
    - secretKey: s3_endpoint
      remoteRef:
        key: backblaze-seafile
        property: endpoint
