apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret-storage.yaml
  - externalsecret-default.yaml
  - externalsecret-monitoring.yaml
  - security-policy-ceph.yaml
  - security-policy-mailpit.yaml
  - security-policy-capacitor.yaml
