---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: spegel
    namespace: spegel
  values:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
    controllers:
      spegel:
        type: daemonset
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        containers:
          spegel:
            imagePullPolicy: IfNotPresent
            securityContext:
              privileged: true
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
                  - SYS_ADMIN
    service:
      enabled: false
