---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 20.8.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${METALLB_INGRESS_ADDR}"
    tlsStore:
      default:
        defaultCertificate:
          secretName: "${SECRET_DOMAIN/./-}-production-tls"
    tlsOptions:
      default:
        minVersion: VersionTLS12
