---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: v1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultSettings:deleting-confirmation-flag: true
  postRenderers:
    - kustomize:
        patchesJson6902:
          - patch:
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: add
                path: /metadata/annotations
                value:
                  metallb.universe.tf/loadBalancerIPs: 192.168.3.129
            target:
              kind: Service
              name: longhorn-frontend
              namespace: longhorn-system
