apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-toolbox
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: node-toolbox
  template:
    metadata:
      labels:
        name: node-toolbox
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: toolbox
          image: ubuntu
          args:
            - sh
            - -c
            - while true; do sleep 50000; done
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: host
              mountPath: /host
      terminationGracePeriodSeconds: 30
      volumes:
        - name: host
          hostPath:
            path: /
