apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: kube-system
  labels:
    name: toolbox
spec:
  nodeName: rory
  containers:
  - name: toolbox
    image: ubuntu
    args:
    - sh
    - -c
    - while true; do sleep 50000; done
    securityContext:
       privileged: true
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /host
        name: host
  volumes:
  - name: host
    hostPath:
      path: /
