---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          route53:
            region: "${AWS_REGION}"
            hostedZoneID: "${AWS_HOSTEDZONE_ID}"
            accessKeyID: "${AWS_ACCESS_KEY}"
            secretAccessKeySecretRef:
              name: letsencrypt-issuer-secret
              key: awsSecretKey
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_LETSENCRYPT_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          route53:
            region: "${AWS_REGION}"
            hostedZoneID: "${AWS_HOSTEDZONE_ID}"
            accessKeyID: "${AWS_ACCESS_KEY}"
            secretAccessKeySecretRef:
              name: letsencrypt-issuer-secret
              key: awsSecretKey
        selector:
          dnsZones:
            - "${SECRET_DOMAIN}"
