apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - webhook-token-externalsecret.yaml
  - webhook-receiver.yaml
  - webhook-alert.yaml
  - webhook-httproute.yaml
  - github-secret-sync-cronjob.yaml
  - networkpolicy.yaml
