---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: oci-webhook-alert
  namespace: flux-system
spec:
  providerRef:
    name: oci-webhook-provider
  eventSeverity: info
  eventSources:
    - kind: OCIRepository
      name: '*'
      namespace: flux-system
    - kind: GitRepository
      name: '*'
      namespace: flux-system
  suspend: false
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: oci-webhook-provider
  namespace: flux-system
spec:
  type: generic
  address: http://notification-controller.flux-system.svc.cluster.local./receiver/oci-webhook-receiver
