---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: chaski
  namespace: chaski
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: chaski
    namespace: chaski
  install:
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    config:
      configPath: /config
      existingConfigMap: chaski-config
    envFrom:
      - secretRef:
          name: holmes-secrets
      - secretRef:
          name: ntfy-token
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
