---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: external-dns-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        credentials: |
          [default]
          aws_access_key_id = {{ .accessKeyID }}
          aws_secret_access_key = {{ .secretAccessKey }}
        region: "{{ .region }}"
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: AWS-DNS-Whoverse
        property: accessKeyID
    - secretKey: secretAccessKey
      remoteRef:
        key: AWS-DNS-Whoverse
        property: secretAccessKey
    - secretKey: region
      remoteRef:
        key: AWS-DNS-Whoverse
        property: region
