---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: 1.14.4
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    interval: 2m
    # logLevel: debug
    provider: aws
    env:
      - name: AWS_DEFAULT_REGION
        valueFrom:
          secretKeyRef:
            name: external-dns-secret
            key: region
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /.aws/credentials

    extraVolumeMounts:
      - name: aws-credentials
        mountPath: /.aws
        readOnly: true
    extraVolumes:
      - name: aws-credentials
        secret:
          secretName: external-dns-secret
    extraArgs:
      - --fqdn-template={{ "{{" }}.Name{{ "}}" }}.ags131.com
    #   - --annotation-filter=external-dns.home.arpa/enabled in (true)
    policy: sync
    sources: ["ingress", "service"]
    txtPrefix: k8s.
    txtOwnerId: default
    domainFilters: ["whoverse.dev", "wg0.dev", "alinanova.dev", "ags131.com"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-secret
