---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-gpu-plugin
  namespace: inteldeviceplugins-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "0.37.1"
    digest: sha256:35195c40cbae8991d82ed16c0df85414f387a777240e220d61b3f294b6b1eed6
  url: oci://ghcr.io/intel/helm-charts/intel-device-plugins-gpu
