---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: intel-gpu-plugin
  namespace: inteldeviceplugins-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: "0.37.0"
    digest: sha256:209a77a29de72667f7e6dfe0b896d6663c2d2c721734527f6c00dc3f4cb79b4f
  url: oci://ghcr.io/intel/helm-charts/intel-device-plugins-gpu
