---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sabnzbd
  namespace: downloads
spec:
  parentRefs:
    - name: internal
      namespace: network
      sectionName: http
    - name: internal
      namespace: network
      sectionName: https
  hostnames:
    - "sabnzbd.whoverse.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sabnzbd
          port: 8080
