---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr-config
  namespace: downloads
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-config
    creationPolicy: Owner
  data:
    - secretKey: apikey
      remoteRef:
        key: prowlarr
        property: credential
