---
apiVersion: v1
kind: Service
metadata:
  name: pve1-egress
  namespace: network
  annotations:
    tailscale.com/tailnet-fqdn: "pve1.tailnet-f088.ts.net."
    tailscale.com/proxy-group: pve-egress
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 8006
      protocol: TCP
    - name: https
      port: 8007
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pve4-egress
  namespace: network
  annotations:
    tailscale.com/tailnet-fqdn: "pve4.tailnet-f088.ts.net."
    tailscale.com/proxy-group: pve-egress
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 8006
      protocol: TCP
    - name: https
      port: 8007
      protocol: TCP
