apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pve-ca
  namespace: network
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pve-ca
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: proxmox-ca-cert
        property: certificate