---
# Downloads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-sabnzbd
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/downloads/sabnzbd
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-sabnzbd
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: downloads-sabnzbd
  resources:
    requests:
      storage: 1Ti
---
# Music (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/music
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-music-downloads
  resources:
    requests:
      storage: 1Ti
---
# Movies - Anime (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-anime-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/movies/anime
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-anime
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-movies-anime-downloads
  resources:
    requests:
      storage: 1Ti
---
# Movies - HD (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-hd-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/movies/hd
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-hd
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-movies-hd-downloads
  resources:
    requests:
      storage: 1Ti
---
# Movies - UHD (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-uhd-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/movies/uhd
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies-uhd
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-movies-uhd-downloads
  resources:
    requests:
      storage: 1Ti
---
# TV - Anime (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-anime-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/tv/anime
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-anime
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-tv-anime-downloads
  resources:
    requests:
      storage: 1Ti
---
# TV - HD (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-hd-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/tv/hd
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-hd
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-tv-hd-downloads
  resources:
    requests:
      storage: 1Ti
---
# TV - Kids (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-kids-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/tv/kids
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-kids
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-tv-kids-downloads
  resources:
    requests:
      storage: 1Ti
---
# TV - Old (downloads namespace)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-old-downloads
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.193
    path: /mnt/tank/media/tv/old
  mountOptions:
    - nfsvers=4
    - nolock
    - soft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv-old
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-tv-old-downloads
  resources:
    requests:
      storage: 1Ti
