---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speedtest-secrets
    creationPolicy: Owner
  data:
    - secretKey: app-key
      remoteRef:
        key: speedtest-tracker
        property: app-key
