---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://raw.githubusercontent.com/openebs/mayastor/v1.0.5/deploy/nats-deployment.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nats
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/ports/0
