apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: error-pages-external
  namespace: network
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: external

  responseOverride:
    - match:
        statusCodes:
          - type: Value
            value: 400
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /400
    - match:
        statusCodes:
          - type: Value
            value: 401
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /401
    - match:
        statusCodes:
          - type: Value
            value: 403
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /403
    - match:
        statusCodes:
          - type: Value
            value: 404
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /404
    - match:
        statusCodes:
          - type: Value
            value: 405
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /405
    - match:
        statusCodes:
          - type: Value
            value: 407
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /407
    - match:
        statusCodes:
          - type: Value
            value: 408
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /408
    - match:
        statusCodes:
          - type: Value
            value: 409
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /409
    - match:
        statusCodes:
          - type: Value
            value: 410
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /410
    - match:
        statusCodes:
          - type: Value
            value: 411
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /411
    - match:
        statusCodes:
          - type: Value
            value: 412
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /412
    - match:
        statusCodes:
          - type: Value
            value: 413
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /413
    - match:
        statusCodes:
          - type: Value
            value: 416
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /416
    - match:
        statusCodes:
          - type: Value
            value: 418
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /418
    - match:
        statusCodes:
          - type: Value
            value: 429
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /429
    - match:
        statusCodes:
          - type: Value
            value: 500
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /500
    - match:
        statusCodes:
          - type: Value
            value: 502
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /502
    - match:
        statusCodes:
          - type: Value
            value: 503
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /503
    - match:
        statusCodes:
          - type: Value
            value: 504
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /504
    - match:
        statusCodes:
          - type: Value
            value: 505
      redirect:
        scheme: http
        hostname: errors.whoverse.nexus
        port: 80
        path:
          type: ReplaceFullPath
          replaceFullPath: /505
