---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
spec:
  selector:
    app: error-pages
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages
spec:
  selector:
    matchLabels:
      app: error-pages
  template:
    metadata:
      labels:
        app: error-pages
    spec:
      containers:
        - name: error-pages
          image: ghcr.io/tarampampam/error-pages:2.20.0
          env:
            - name: TEMPLATE_NAME
              value: lost-in-space
            - name: SHOW_DETAILS
              value: "false"
          resources:
            requests:
              cpu: 100m
              memory: 50m
