---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: low-resources
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 256Mi
