---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: weave-gitops
spec:
  parentRefs:
    - name: internal
      namespace: networking
  hostnames:
    - gitops.ags131.com
  rules:
    - backendRefs:
        - name: weave-gitops
          port: 9001
