---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whoverse-nexus-wildcard-tls
  namespace: network
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: whoverse-nexus-wildcard-tls
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: whoverse-nexus-cf-origin-cert
        property: file/tls.crt
    - secretKey: tls.key
      remoteRef:
        key: whoverse-nexus-cf-origin-cert
        property: file/tls.pem