---
apiVersion: v1
kind: Namespace
metadata:
  name: towonel
  labels:
    homelab.whoverse.dev/component: apps
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
