clusterName: whoverse
talosVersion: v1.3.3
kubernetesVersion: v1.26.0
endpoint: https://kube.${domainName}:6443
allowSchedulingOnMasters: true
additionalMachineCertSans:
  - 192.168.3.2
additionalApiServerCertSans:
  - 192.168.3.2
  - kube.${domainName}
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
nodes:
  - hostname: rory
    ipAddress: 192.168.3.3
    controlPlane: true
    installDisk: /dev/mmcblk0
    patches:
    - '@./common-patch.yaml'
    - |-
      - op: add
        path: /machine/network/interfaces/0/addresses
        value:
        - 192.168.3.3/24
      - op: add
        path: /machine/type
        value: init
    # machine type to init bootstraps automatically
  - hostname: amy
    ipAddress: 192.168.3.4
    controlPlane: true
    installDisk: /dev/mmcblk0
    patches:
    - '@./common-patch.yaml'
    - |-
      - op: add
        path: /machine/network/interfaces/0/addresses
        value:
        - 192.168.3.4/24
  - hostname: river
    ipAddress: 192.168.3.5
    controlPlane: true
    installDisk: /dev/mmcblk0
    patches:
    - '@./common-patch.yaml'
    - |-
      - op: add
        path: /machine/network/interfaces/0/addresses
        value:
        - 192.168.3.5/24

controlPlane:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
          rotate-server-certificates: "true"
worker:
  patches:
    - |-
      - op: add
        path: /machine/kubelet/extraArgs
        value:
          feature-gates: GracefulNodeShutdown=false,MixedProtocolLBService=false
          rotate-server-certificates: "true"
