---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.whoverse.dev/component: infrastructure
