---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "2.7.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    installCRDs: true
    resources:
      requests:
        memory: 64Mi
    webhook:
      resources:
        requests:
          memory: 64Mi
    certController:
      resources:
        requests:
          memory: 64Mi
