---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-secrets
    namespace: external-secrets-system
  install:
    crds: Create
    createNamespace: false
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  values:
    installCRDs: true
    resources:
      requests:
        memory: 64Mi
    webhook:
      resources:
        requests:
          memory: 64Mi
    certController:
      resources:
        requests:
          memory: 64Mi
