apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: flux-system
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from pods within the same namespace
    - from:
      - podSelector: {}
    # Allow traffic from any namespace (for gateway access)
    - from:
      - namespaceSelector: {}
  egress:
    - {}
