apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  # - openebs-localpv/ks.yaml  # disabled pending cluster reset
  # - rook-ceph/ks.yaml  # disabled pending cluster reset
  - miroir/ks.yaml
