---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    homelab.whoverse.dev/component: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    homelab.whoverse.dev/component: infrastructure
