---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yuvomi-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: yuvomi-secrets
    creationPolicy: Owner
  data:
    - secretKey: sessionSecret
      remoteRef:
        key: yuvomi-secrets
        property: sessionSecret
    - secretKey: dbEncryptionKey
      remoteRef:
        key: yuvomi-secrets
        property: dbEncryptionKey
    - secretKey: googleClientId
      remoteRef:
        key: google-api-oauth
        property: clientId
    - secretKey: googleClientSecret
      remoteRef:
        key: google-api-oauth
        property: clientSecret
    - secretKey: oidcClientSecret
      remoteRef:
        key: kanidm-oauth2
        property: yuvomi-secret
