---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yuvomi-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: yuvomi-secrets
    creationPolicy: Owner
  data:
    - secretKey: sessionSecret
      remoteRef:
        key: yuvomi-secrets
        property: sessionSecret
    - secretKey: dbEncryptionKey
      remoteRef:
        key: yuvomi-secrets
        property: dbEncryptionKey
