apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-secrets
    creationPolicy: Owner
  data:
  - secretKey: "DATABASE_PASSWORD"
    remoteRef:
      key: "immich"
      property: "database_password"
  - secretKey: "DATABASE_USERNAME"
    remoteRef:
      key: "immich"
      property: "database_username"
  - secretKey: "JWT_SECRET"
    remoteRef:
      key: "immich"
      property: "jwt_secret"
  - secretKey: "REDIS_PASSWORD"
    remoteRef:
      key: "immich"
      property: "redis_password"
