---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkstack-app-key
  namespace: default
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: linkstack-app-key
    creationPolicy: Owner
  data:
    - secretKey: app-key
      remoteRef:
        key: linkstack-app-key
        property: password
