---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: downloads-storage
  namespace: downloads
spec:
  interval: 15m
  path: "./apps/downloads/storage/config"
  sourceRef:
    kind: OCIRepository
    name: home-ops
    namespace: flux-system
  timeout: 5m
  wait: true
  prune: false
