---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-longhorn
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/longhorn-system/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  patches:
  - patch: |-
     - op: add
       path: /spec/type
       value: LoadBalancer
      - op: add
        path: /metadata/annotations
        value:
          metallb.universe.tf/loadBalancerIPs: 192.168.3.129
    target:
      kind: Service
      name: longhorn-frontend
      namespace: longhorn-system
