---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze-backup-creds
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: backblaze-backup-creds
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: backblaze-k8s-backup
        property: key-id
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: backblaze-k8s-backup
        property: credential
