---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: immich-password-gen
  namespace: databases
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: paperless-password-gen
  namespace: databases
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-password-gen
  namespace: databases
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: vikunja-password-gen
  namespace: databases
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: kasm-password-gen
  namespace: databases
spec:
  length: 32
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
