---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-user-password-push
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: immich-user-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: immich-postgres
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: paperless-user-password-push
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: paperless-user-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: paperless-postgres
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-user-password-push
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik-user-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: authentik-postgres
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: vikunja-user-password-push
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: vikunja-user-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: vikunja-postgres
          property: password
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kasm-user-password-push
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: kasm-user-password
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: kasm-postgres
          property: password
