---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-hub-secrets
  namespace: towonel
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: towonel-hub-secrets
    creationPolicy: Owner
  data:
    - secretKey: TOWONEL_IDENTITY_KEY
      remoteRef:
        key: towonel-hub
        property: NODE_IDENTITY_KEY
    - secretKey: TOWONEL_HUB_OPERATOR_API_KEY
      remoteRef:
        key: towonel-hub
        property: OPERATOR_API_KEY
    - secretKey: TOWONEL_HUB_KEK
      remoteRef:
        key: towonel-hub
        property: HUB_KEK
    - secretKey: TOWONEL_INVITE_HASH_KEY
      remoteRef:
        key: towonel-hub
        property: INVITE_HASH_KEY
    - secretKey: TOWONEL_HUB_LINK_PSK
      remoteRef:
        key: towonel-hub
        property: HUB_LINK_PSK
