apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect
    namespace: onepassword-connect
type: Opaque
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:7tNVu0+ROoe4mBOpcNfPz/bldaRjKT7ibaJpy1VzXnUWP+nNx3bXfGIRMnOyoUoXJujC9ZmKx+/iUEsPEzhwuxFgvO28RkVyqBCYoU/AwqTLvsv8ducLd52xzavaUBOPlQQF4pp8kwZJnbW/Wo1raEuE1LoMFHpwMsawdn6/dADWH+vJghKgt9hMCqEo52guOb8m+2xhPwgQlETmrwvj/XV1NIHTUk/I8nqC0pTsJJNrmMMk7F1eR8J5imWNS4UF3nsBzU+MdH9gHt2snVshbTWw9xTDUNhhIgg1tJWPAgsKX7b7tKmgBRGgEG4KKkyta7a6hZdxXOaJk6T3omOqNT4LVvjrPGdX87xKWZz2pg7Qx05R4As6TNCHE3HYd5CcSYbQJk2nL027wd3Mq2WyGJlIcKG1HvjcLmKTziZOSFIsWaIiLO6z/NLmQvug+qh6JlR9sRMXdlGqw21CNJ7u86t+VDG9FjR9mgxe3kK/RLBgkOPHHFC2UV+kmdaHOaepcBAggodDCqnRgDzoxdiFzm3sOKcpZhtPkbFs9LyptOgGAKy106e4AfYJbeYtSNfumulOYoqD+Z9jAZj3Be92Vx4wVGGZqCfZH3H+8TLyFlHobvM0CBJi89Jgx2cLK8Tw2lK4oldHfzAP/tNCHVXuxjLGjsHJozHj6KQRWwnzJGwBk13NtZDXzp3FTxpT+5bx973txYhNUnniFf/qFDu6iUOfnHNfAFHIDUEUKO0VTvG44IPfEht61uJYZpVFCe8URkprCIFyHf++mGYPoaMNozE4aUgp51RZQFfKDS55H+yJFvohO+6zUJ+ZGEf1A1hUJsiMnBBs6EBcav3wLOGa9MhGJNurQ9SBe4DYTANv1J1aN0Fn9rvMZ2AmlmFiSwoLLEOd+otCs8Zro95TkdBMEryxcVK0XMUPoup3tbWUFA3rlAiBvS6vHDZP5WnHDypFwVZsTST2Pavfp1na/wfc9RetN3xRZSOpR8wLkT+tq7k4Ot3XEsxrftKpY4q5ZXIr5tBx8Pvf2Nl9PNGQVz0JOU4Vi/kFdzNxfx36h3wxwEqcLSaP9Bvr/6cCLWPtxpcDiQjJyd9Cp5VlIBs5/X8kG+1qCEKq7KXdmsDdz2EbCMnUsfjvmHXfX4iEFF6Exq2LHW0/2tlRQ5oh++WE490ObMZo3VpNG1BJNtYZvrcLTzvezHofJU+Wpt3A9oWC27CjK+tMUiRjTvQ5CLF8DMCZ+UZG1JVNpOHp3J22McK6XQHCAYC85PovJ8IPiRT0SolVMJZsQD6BfLfL5/hXuM+3UIh/dIJF9Y8ckLEXxPD+pWaiRzjo7YGr9N1494N54K7uTkpD5uUpolSh00X6G1FqSR6m1iDgycFo1DDAfqB8VdGMqFweL6MEwD6NSbTMDjm2LuxOaToU8G+aew/BnXZpD8HHj6H5qfa+9wBdjs/J0g==,iv:bKNAvUx4J9AWTY69v0PPT3rvIDuvInHKJ/Q5cwCl6aY=,tag:kATj803j8Y6JIWQfRxb5LQ==,type:str]
    token: ENC[AES256_GCM,data:YTBd9QE6EgCNT5xzCSHBMrGL4y6Ib1DncuMzEswXrBfJNd32tE+Rj1VzViKDL80ra9FeD35ImbVJj2vpiYjzvhjf1o/Jofgk7a6kJAXGdDfXXlvOr4pnSGEyVtBQLucVZy9AEjbXgHe42/CtArwAWHq+eGbLgDjUpKfsNdu1CBvQMnahN4mWLU6uKMJcEbyt6HIZPhSsmJEoHbKkWtzLzSUwf/9NwiRr6yHP71MKsP7DfXBYwkB+XNlL/5zsafA2BK+V+IwRYX57FXlimFwK/X7LvIEigLNONrqsf0ob/8j+5ebWmq4nEHdBu01FvOFMG+OXv6aDZdrrXd4FTDlO747E4ZILU0GRjyTx8k72jJXNCI/GMm1CSsQh5ZgYE/z39x3qPjbZgA+KCI6JLRW2/RcUeyizQMwkHjMqZhi2sMPeWpC54SU4SkFz0qmASs44kYto1rZnKJSxTtYOAt4nC8L97dwnMna9jHhcA4Hoo+ZTDjADBG9ZRfu7VnnwdHEH12zs9qwMNsHdmpGVzxDvZ+Xv4bqO/Dp9b1En3tRpSaaw+J6SIUdjklrNlPCxr0ON0XU5tPcjVu4br6sziMpEm87bDTWWetV5eNBzHoEnMCZ4ZzNZQM9MgyrU3fF1BI9e2mlp8mzDCLLmn3IBHpl3DhGvJvgKbJz0AZ3a443Nj7uhHEZ4r86Hy4+4XIZ0g446RUz6sgKx/ketXoUFXu38c3mn+YKUa1gecc8plsYpANm1wFd/xW9XItK+y9bmNc1xrmB/aUXMone19eA0T4cOlYhkBICm6nUv/8c4jVhecgolKKZIYIbvjPPXmOHIAOfJnssUak19+9JeVEk/cdcvXuxhcA==,iv:2XPFP2ISKeryswU1K4JoeRYBIJqjwtImZubFckJ+EVg=,tag:rdcsIOx8+3nbuc3+t5DG/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTlZGY01OSFV0ckljUHFN
            OW5PbWw5V1R3REVkc2w5L0hKdHhOSFRVaURjCjdxQXNqSmp3ZEovRVU5RkJFcklS
            dE9zNXNFMkx2MXdzQkJINXRvcWNiakkKLS0tIFFDK3JQa1FaNVREN2dBejdmN3J2
            N0JyZWdCNnhhRHV5TFJhalIzeG1FK2sKOqkcUZib72O57qOdXggyIUH9fdiyvEdW
            SJYxGJ7D5y4otU8HyXvQWYQIK0DquScYTAp+I8ZfQhrF/sunp7aHyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16865gej0ndnlnghdq347fur59ht8d7wrcfptdw5ja4fhc4lwdfpq59ratl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVWNjaGVkbEhKSXZDaWlo
            enNXZHd5ZFcvVXY1bFdKajJleFlMZndrMzJRCnRjcFFJcG9RRFZNK2RtVVAvaUlM
            cjhNay8vc1F5WTBXUU9ERkx1aklVS3MKLS0tIGpJQW0wWHhEVnBaV1lwL3VkdytY
            ZU5WN082cEFpR2VudjdWMmYyNWlTczAK50j9PM6mmZnwDcB4luTNDiqdxz3WJp7n
            uOHHN+qWAeIWkMIoBj6oPjcN5GiCTfd5UXy0or5MPL48150UdxZ4iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1maj5j0km9m39u7l2fxy5dyvuah79ewfvqa0wq69wdxsd6dqdtcaqe0e6dq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T23:43:14Z"
    mac: ENC[AES256_GCM,data:YMVPQdBqF4XiI5cZ47kJDdyOg86Uuz510ZVk3A0ZC6yJ71SuZXTdI3nsmLjqmObZyH+5vYU8nXUXjKEmizvhB3p4Ej4aNq/H61ztcxNxSNihHNYFFHx+2PQWNPnHYvKpx7FUDmQ1mvdpjnAe5LG+mbd3oc/vRbonwq8QxgBM1wY=,iv:BqLph6vSMfPRT9YeZTultCpb6PRqmp5SiC3PQpp7A2Y=,tag:eijC2I9brSfHWhzVDjI2kQ==,type:str]
    pgp:
        - created_at: "2026-08-19T23:43:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DzCc2EjPFSlYSAQdAK2rlzyWQmn5qpb1rIRsEjP8LyHnwrPbgl4t6SyMRGFgw
            X0com6DjbzD8xZmcJj439AUbOxqg6SLhuic5/RAhM6+nstO59mz+K6UrabnFB8BD
            0l4BRiZT3Dy1sssJKjY+r+h+bX/Z9mOK53SK/Ou8C6Ol1Voi7NLHWgtzaLW2WjUk
            qTuc0/DndKegXsnPpzATBOLUCgayPy0waZS7/z9Ri11hcv/k3odtmZnz2JNeHmeG
            =Okem
            -----END PGP MESSAGE-----
          fp: B2266723EDB691FBB16501BC07D6E31CCAE33514
    version: 3.13.3
