---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - barcodebuddy/ks.yaml
  - grocy/ks.yaml
  - konflate/ks.yaml
  - linkstack/ks.yaml
  - mailpit/ks.yaml
  - trilium/ks.yaml
  #- memos/ks.yaml
  - speedtest-tracker/ks.yaml
  - yuvomi/ks.yaml
