apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - barcodebuddy/ks.yaml
  - database/ks.yaml
  - error-pages/ks.yaml
  - grocy/ks.yaml
  - mailpit/ks.yaml
  #- memos/ks.yaml
  - speedtest-tracker/ks.yaml
