---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dex-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTH0_CLIENT_ID: "{{ .CLIENT_ID }}"
        AUTH0_CLIENT_SECRET: "{{ .CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: auth0-dex
