---
# yaml-language-server: $schema=https://kubernetes-schemas.whoverse.dev/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app dex
  namespace: dex
spec:
  interval: 15m
  chart:
    spec:
      chart: dex
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      storage:
        type: kubernetes
        config:
          inCluster: true
    ingress:
      enabled: true
      className: traefik
      annotations:
        external-dns.home.arpa/enabled: "true"
        hajimari.io/icon: mdi:code-json
      hosts:
        - host: &host "auth.whoverse.dev"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi
