---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-mirror
  namespace: kopiur-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopiur-mirror-secret
    creationPolicy: Owner
  data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        key: volsync-kopia-password
        property: password
    - secretKey: GARAGE_ACCESS_KEY_ID
      remoteRef:
        key: nas-garage-key
        property: key-id
    - secretKey: GARAGE_SECRET_ACCESS_KEY
      remoteRef:
        key: nas-garage-key
        property: credential
    - secretKey: B2_ACCESS_KEY_ID
      remoteRef:
        key: backblaze-k8s-backup
        property: key-id
    - secretKey: B2_SECRET_ACCESS_KEY
      remoteRef:
        key: backblaze-k8s-backup
        property: credential
