apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- ai
  - default
  #- docs
  - downloads
  - entertainment
  #- homepage
  #- immich
  #- plex
  #- n8n
  #- kasm
  - sync
