---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kro
  namespace: kro-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.9.3
    digest: sha256:e0a333049dc8f92f1485b550554344eca90856377fa3c3868d558b5aa25880fb
  url: oci://registry.k8s.io/kro/charts/kro
