---
apiVersion: v1
kind: Namespace
metadata:
  name: inteldeviceplugins-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    homelab.whoverse.dev/component: infrastructure
    pod-security.kubernetes.io/enforce: privileged
