---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-ntfy
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-ntfy
    creationPolicy: Owner
  data:
    - secretKey: NTFY_TOKEN
      remoteRef:
        key: ntfy-gatus-token
        property: token