apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sympozium
  namespace: ai
spec:
  interval: 30m
  chart:
    spec:
      chart: sympozium
      version: "0.10.43"
      sourceRef:
        kind: HelmRepository
        name: sympozium
        namespace: flux-system
      interval: 24h
  values:
    agentSandbox:
      enabled: true
      defaultRuntimeClass: gvisor
      rbac: true
    createNamespace: true
    namespace: sympozium-system
    namespaceLabels:
      pod-security.kubernetes.io/enforce: baseline
    certManager:
      enabled: true
      issuer:
        kind: Issuer
        name: sympozium-selfsigned
        selfSigned: true
    apiserver:
      webUI:
        enabled: true
    networkPolicies:
      enabled: false
    defaultPolicies:
      enabled: true
    defaultSkills:
      enabled: true
    defaultPersonas:
      enabled: false
    defaultMcpServers:
      enabled: true
    observability:
      enabled: false
    nodeProbe:
      enabled: false
  install:
    createNamespace: true
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m
  upgrade:
    remediation:
      retries: 3
    strategy:
      name: RetryOnFailure
      retryInterval: 5m