apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sympozium
  namespace: sympozium-system
spec:
  parentRefs:
    - name: internal
      namespace: network
      sectionName: http
    - name: internal
      namespace: network
      sectionName: https
  hostnames:
    - sym.whoverse.dev
  rules:
    - backendRefs:
        - name: sympozium-apiserver
          port: 8080