apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sympozium-ui-token-push
  namespace: sympozium-system
spec:
  refreshInterval: 24h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: sympozium-ui-token
  data:
    - match:
        secretKey: token
        remoteRef:
          remoteKey: sympozium-web-ui
          property: password