---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kopia-ui-auth-push
  namespace: kopiur-system
spec:
  refreshInterval: 24h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: whoverse-kopia-ui-auth
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: kopia-ui-auth
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: kopia-ui-auth
          property: password
