{
 "title": "Radarr v3",
 "description": "This is a dashboard for Radarr v3 (exportarr does not work with Radarr v2). You will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.\r\n\r\nBased on: https://grafana.com/grafana/dashboards/12530",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"radarr_.*\"}, job)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Movies Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_queue_total{job=\"$Instance\"} OR on() vector(0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "radarr_history_total{job=\"$Instance\"}",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_movie_missing_total{job=\"$Instance\"}",
     "legendFormat": "Missing"
    },
    {
     "expr": "radarr_movie_monitored_total{job=\"$Instance\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "radarr_movie_total{job=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_movie_filesize_total{job=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Episode quality",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 3, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort_desc(sum(radarr_movie_quality_total{job=\"$Instance\"}) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "radarr_rootfolder_freespace_bytes{job=\"$Instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}