{
 "title": "Sonarr v3 + Selector",
 "description": "This is a dashboard for Sonarr v3 (exportarr does not work with Sonarr v2). You will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.\r\n\r\nA copy of https://grafana.com/grafana/dashboards/12530-sonarr-v3/ I just added the ability to switch between multiple instances of sonarr being exported. I wish I could PR it or something.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values({__name__=~\"sonarr_.*\"}, job)"
    }
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Show Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_queue_total{job=\"$Instance\"} OR vector(0)",
     "legendFormat": "Queued"
    },
    {
     "expr": "sonarr_history_total{job=\"$Instance\"}",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_series_monitored_total{job=\"$Instance\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sonarr_series_total{job=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Seasons",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_season_monitored_total{job=\"$Instance\"}",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sonarr_season_total{job=\"$Instance\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_episode_downloaded_total{job=\"$Instance\"}",
     "legendFormat": "Downloaded"
    },
    {
     "expr": "sonarr_episode_total{job=\"$Instance\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "sonarr_episode_missing_total{job=\"$Instance\"}",
     "legendFormat": "Missing"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_series_filesize_bytes{job=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "Episode quality",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 8, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(sonarr_episode_quality_total{job=\"$Instance\"}) by (quality))",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Storage Available",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sonarr_rootfolder_freespace_bytes{job=\"$Instance\"}",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}