---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: home-ops
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/alinanova21/home-ops
  ref:
    tag: latest
    digest: sha256:627f3dc41a9a917f8b89eeefd41b2e33fcd1b947846fae2cc97579f38ef3d7b6