---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-gateway-api
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
    require-cni.flux.home.arpa/disabled: "true"
spec:
  path: ./kubernetes/apps/networking/gateway-api/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-gateway-api-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/networking/gateway-api/config
  prune: true
  dependsOn:
    - name: cluster-apps-gateway-api
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
