name: doc-site

on:
  push:
    branches:
      - main
    paths:
      - 'doc-site/**'
      - 'kubernetes/**'
      - '.github/workflows/doc-site.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Login to GitHub Container Registry
        uses: docker/login-container-registry@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flate
        uses: home-operations/flate/action@06066be860f567b325cd71dda35ed9fc9afd039b # main
        with:
          command: build all --path ./kubernetes -o json
          output-file: doc-site/public/flate-output.json

      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: ./doc-site
          file: ./doc-site/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/doc-site:latest
            ghcr.io/${{ github.repository }}/doc-site:${{ github.sha }}
