---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-k8s-operator
        property: username
    - secretKey: client_secret
      remoteRef:
        key: tailscale-k8s-operator
        property: credential
