---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr-hd
  namespace: downloads
spec:
  targetNamespace: downloads
  components:
        - ../../../components/kopiur/backup
  interval: 15m
  path: "./downloads/sonarr-hd/app"
  postBuild:
    substitute:
      APP: sonarr-hd
  sourceRef:
    kind: OCIRepository
    name: home-ops
    namespace: flux-system
  timeout: 10m
  wait: true
  prune: false
