---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.6.1/standard-install.yaml
  - ./gatewayclass.yaml
  - ./gateway.yaml
