apiVersion: v1alpha1
kind: KubeAuthenticationConfig
configuration:
  jwt:
    - issuer:
        url: https://idm.whoverse.nexus/oauth2/openid/kubernetes
        audiences:
          - kubernetes
      claimMappings:
        username:
          claim: email
          prefix: ""
        groups:
          claim: groups
          prefix: ""
